server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitybasic?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 428834061816-qnercs6b7a9jr4ihboacim4cn4gmt4o3.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 375215797390135
            client-secret: 9e77c6d4994366069fc72ee86602953a
            scope:
            - email
            - public_profile
          naver:
            client-id: UNyz1Fl5xBqqUdSyRfzR
            client-secret: ecgxX0SX0T
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 받는데 response 라는 키 값으로 네이버가 리턴해줌