server:
  port: 8761

# ???? ???? ???? ??? ??????,
# ??? ???????? ID? ???? ???,
# ? ID?? application > name ??? ?? ID? ??? ? ??
# ? ?????? ID ? "discoveryservice" ? ???. (????)
spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false